Algoritmo "EX008"

var nome, endereco, tel: caracter

Inicio

    //ENTRADA
    escreva("Informe seu Nome: ")
    leia(nome)

    escreva("Informe seu endereço: ")
    leia(endereco)
    
    escreva("Digite seu número de telefone com o DDD do seu estado: ")
    leia(tel)

    //SAÍDA
    escreval("Suas informações:")
    escreval("Nome: ", nome)
    escreval("Endereço: ", endereco)
    escreval("Telefone: ", tel)

Fimalgoritmo